language: node_js
node_js:
   - '9'
dist: trusty
sudo: required
branches:
only:
  - master
before_install:
  - gem install rake
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --base-href https://nayfin.github.io/tft/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/apps/documentation/
  on:
    branch: master